image: node:16.13.0
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli
    - npm i
    - npm run buildProd
  artifacts:
    paths:
      - public
  only:
    - pipe_monitoring